site_name: IoT Framework
nav:

  - Home: 
      Introduction: index.md
      Setup:
        Getting Started: 
          ESP: setup/setup_esp.md
          AWS: setup/setup_aws.md
        Structure: setup/structure.md
        Coding Style: 
          C++: setup/coding-style/cpp.md
          Git: setup/coding-style/git.md
        Documentation: setup/documentation.md
  - Core: https://ece-iot.github.io/esp-iot-framework/core/
  - Sensors: https://ece-iot.github.io/esp-iot-framework/sensors/
  - AWS: https://ece-iot.github.io/aws-iot-framework/aws/cli/configuration-basics/
  - Alexa: https://ece-iot.github.io/aws-iot-framework/alexa/


repo_url: https://github.com/ECE-IoT/ECE-IoT.github.io

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - git-revision-date
  - mkdocstrings
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(window.localStorage.getItem('/.__palette')).index == 1) ? 'dark' : 'light'

markdown_extensions:
  - footnotes
  - admonition
  - def_list
  - attr_list
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
